### ISSUE TITLE
Request for Fader Level Variables

### ISSUE THREAD

**Issue by samuraitheta** [bitfocus/companion-module-soundcraft-ui#81] opened 2024-02-22 05:37 UTC
Hello!

Thank you again! I would love to have variables for fader levels, that way I can see what level each of my channels is at. 

Regards,
Matthew

**Comment by fmalcher** [comment] 2024-02-22 12:20
Duplicate of https://github.com/bitfocus/companion-module-soundcraft-ui/issues/54.
Please see this issue for more info about the blocking aspects of this story. 🙂

**Closed** 2024-02-22 12:20 UTC
